package com.hrhousing.app.ui.screens.checkin

import androidx.compose.foundation.layout.Arrangement
import androidx.compose.foundation.layout.Row
import androidx.compose.foundation.layout.Spacer
import androidx.compose.foundation.layout.fillMaxWidth
import androidx.compose.foundation.layout.height
import androidx.compose.foundation.layout.padding
import androidx.compose.foundation.lazy.LazyColumn
import androidx.compose.material3.Checkbox
import androidx.compose.material3.Divider
import androidx.compose.material3.MaterialTheme
import androidx.compose.material3.OutlinedTextField
import androidx.compose.material3.Text
import androidx.compose.runtime.Composable
import androidx.compose.runtime.collectAsState
import androidx.compose.runtime.getValue
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.unit.dp
import androidx.lifecycle.viewmodel.compose.viewModel
import com.hrhousing.app.AppContainer
import com.hrhousing.app.ui.AppViewModelFactory
import com.hrhousing.app.ui.components.CopyableTextBlock
import com.hrhousing.app.ui.components.TimeTextField

@Composable
fun CheckinInfoScreen(container: AppContainer) {
    val viewModel: CheckinInfoViewModel = viewModel(factory = AppViewModelFactory(container))
    val local by viewModel.local.collectAsState()
    val shared by viewModel.sharedFields.collectAsState()
    val template by viewModel.template.collectAsState()
    val generated by viewModel.generatedText.collectAsState()

    LazyColumn(modifier = Modifier.fillMaxWidth().padding(16.dp)) {
        item {
            OutlinedTextField(shared.complexName, viewModel::setComplexName, label = { Text("ЖК") }, modifier = Modifier.fillMaxWidth())
            Spacer(Modifier.height(8.dp))
            OutlinedTextField(shared.address, viewModel::setAddress, label = { Text("Адрес") }, modifier = Modifier.fillMaxWidth())
            Spacer(Modifier.height(8.dp))

            Row(horizontalArrangement = Arrangement.spacedBy(8.dp)) {
                OutlinedTextField(
                    local.entrance,
                    { v -> viewModel.updateLocal { it.copy(entrance = v) } },
                    label = { Text("Подъезд") },
                    modifier = Modifier.weight(1f),
                )
                OutlinedTextField(
                    local.entranceNote,
                    { v -> viewModel.updateLocal { it.copy(entranceNote = v) } },
                    label = { Text("Примечание") },
                    modifier = Modifier.weight(1f),
                )
            }
            Spacer(Modifier.height(8.dp))
            Row(horizontalArrangement = Arrangement.spacedBy(8.dp)) {
                OutlinedTextField(
                    local.floor,
                    { v -> viewModel.updateLocal { it.copy(floor = v) } },
                    label = { Text("Этаж") },
                    modifier = Modifier.weight(1f),
                )
                OutlinedTextField(
                    local.apartmentNumber,
                    { v -> viewModel.updateLocal { it.copy(apartmentNumber = v) } },
                    label = { Text("Номер квартиры") },
                    modifier = Modifier.weight(1f),
                )
            }
            Spacer(Modifier.height(8.dp))
            OutlinedTextField(
                local.intercomCode,
                { v -> viewModel.updateLocal { it.copy(intercomCode = v) } },
                label = { Text("Код домофона") },
                modifier = Modifier.fillMaxWidth(),
            )
            Spacer(Modifier.height(16.dp))

            Row(horizontalArrangement = Arrangement.spacedBy(8.dp)) {
                TimeTextField("Время заселения (с)", shared.checkinTime, viewModel::setCheckinTime, Modifier.weight(1f))
                TimeTextField("Время выселения (до)", shared.checkoutTime, viewModel::setCheckoutTime, Modifier.weight(1f))
            }
            Spacer(Modifier.height(16.dp))

            Row(horizontalArrangement = Arrangement.spacedBy(8.dp)) {
                OutlinedTextField(
                    local.twoGisLinkText,
                    { v -> viewModel.updateLocal { it.copy(twoGisLinkText = v) } },
                    label = { Text("Ссылка 2ГИС — текст") },
                    modifier = Modifier.weight(1f),
                )
                OutlinedTextField(
                    local.twoGisLinkUrl,
                    { v -> viewModel.updateLocal { it.copy(twoGisLinkUrl = v) } },
                    label = { Text("Ссылка 2ГИС — URL") },
                    modifier = Modifier.weight(1f),
                )
            }
            Spacer(Modifier.height(8.dp))
            Row(horizontalArrangement = Arrangement.spacedBy(8.dp)) {
                OutlinedTextField(
                    local.wifiName,
                    { v -> viewModel.updateLocal { it.copy(wifiName = v) } },
                    label = { Text("Имя Wi-Fi сети") },
                    modifier = Modifier.weight(1f),
                )
                OutlinedTextField(
                    local.wifiPassword,
                    { v -> viewModel.updateLocal { it.copy(wifiPassword = v) } },
                    label = { Text("Пароль Wi-Fi") },
                    modifier = Modifier.weight(1f),
                )
            }
            Spacer(Modifier.height(8.dp))

            Row(verticalAlignment = Alignment.CenterVertically) {
                Checkbox(checked = local.includeRulesBlock, onCheckedChange = { v -> viewModel.updateLocal { it.copy(includeRulesBlock = v) } })
                Text("Включить стандартный блок правил проживания")
            }
            Spacer(Modifier.height(8.dp))

            OutlinedTextField(
                local.additionalComment,
                { v -> viewModel.updateLocal { it.copy(additionalComment = v) } },
                label = { Text("Дополнительный комментарий") },
                modifier = Modifier.fillMaxWidth(),
                minLines = 2,
            )
            Spacer(Modifier.height(20.dp))
            Divider()
            Spacer(Modifier.height(12.dp))

            Text("Шаблон (редактируемый, токены вида {жк}, {адрес}, {дата_заезда}…)", style = MaterialTheme.typography.titleSmall)
            Spacer(Modifier.height(8.dp))
            OutlinedTextField(
                value = template,
                onValueChange = viewModel::updateTemplate,
                modifier = Modifier.fillMaxWidth(),
                minLines = 6,
            )
            Spacer(Modifier.height(16.dp))

            Text("Готовый текст", style = MaterialTheme.typography.titleSmall)
            Spacer(Modifier.height(8.dp))
            CopyableTextBlock(generated)
            Spacer(Modifier.height(32.dp))
        }
    }
}
