package com.hrhousing.app.ui.screens.finance

import androidx.activity.compose.rememberLauncherForActivityResult
import androidx.activity.result.contract.ActivityResultContracts
import androidx.compose.foundation.layout.Arrangement
import androidx.compose.foundation.layout.Row
import androidx.compose.foundation.layout.Spacer
import androidx.compose.foundation.layout.fillMaxWidth
import androidx.compose.foundation.layout.height
import androidx.compose.foundation.layout.padding
import androidx.compose.foundation.lazy.LazyColumn
import androidx.compose.foundation.lazy.items
import androidx.compose.foundation.text.KeyboardOptions
import androidx.compose.material3.Button
import androidx.compose.material3.Card
import androidx.compose.material3.Checkbox
import androidx.compose.material3.Divider
import androidx.compose.material3.IconButton
import androidx.compose.material3.MaterialTheme
import androidx.compose.material3.OutlinedButton
import androidx.compose.material3.OutlinedTextField
import androidx.compose.material3.Text
import androidx.compose.material.icons.Icons
import androidx.compose.material.icons.filled.Close
import androidx.compose.material3.Icon
import androidx.compose.runtime.Composable
import androidx.compose.runtime.collectAsState
import androidx.compose.runtime.getValue
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.platform.LocalContext
import androidx.compose.ui.text.input.KeyboardType
import androidx.compose.ui.unit.dp
import androidx.lifecycle.viewmodel.compose.viewModel
import com.hrhousing.app.AppContainer
import com.hrhousing.app.data.db.entity.ApartmentType
import com.hrhousing.app.data.db.entity.label
import com.hrhousing.app.data.shared.checkinDate
import com.hrhousing.app.data.shared.checkoutDate
import com.hrhousing.app.data.shared.total
import com.hrhousing.app.ui.AppViewModelFactory
import com.hrhousing.app.ui.components.AutosuggestTextField
import com.hrhousing.app.ui.components.CopyableTextBlock
import com.hrhousing.app.ui.components.DateField
import com.hrhousing.app.ui.components.MoneyField
import com.hrhousing.app.ui.components.TilePicker
import com.hrhousing.app.util.TimeUtils
import com.hrhousing.app.util.excel.ExcelService
import com.hrhousing.app.util.formatMoney

@Composable
fun FinanceApprovalScreen(container: AppContainer) {
    val viewModel: FinanceApprovalViewModel = viewModel(factory = AppViewModelFactory(container))
    val shared by viewModel.sharedFields.collectAsState()
    val extras by viewModel.extraObjects.collectAsState()
    val template by viewModel.template.collectAsState()
    val generated by viewModel.generatedText.collectAsState()
    val cityOptions by viewModel.cityOptions.collectAsState()
    val mainGuests by viewModel.mainGuestsCount.collectAsState()
    val registry by viewModel.registry.collectAsState()
    val checkedIds by viewModel.checkedRegistryIds.collectAsState()
    val context = LocalContext.current

    val exportLauncher = rememberLauncherForActivityResult(
        ActivityResultContracts.CreateDocument("application/vnd.openxmlformats-officedocument.spreadsheetml.sheet"),
    ) { uri ->
        uri?.let { ExcelService.exportFinanceRegistry(context, it, registry) }
    }

    LazyColumn(modifier = Modifier.fillMaxWidth().padding(16.dp)) {
        item {
            Text("Основной объект", style = MaterialTheme.typography.titleMedium)
            Spacer(Modifier.height(8.dp))
            AutosuggestTextField("Город", shared.city, viewModel::setCity, cityOptions, Modifier.fillMaxWidth())
            Spacer(Modifier.height(8.dp))
            Text("ФИО: ${shared.guestNames.filter { it.isNotBlank() }.joinToString(", ").ifBlank { "—" }}", style = MaterialTheme.typography.bodyMedium)
            Spacer(Modifier.height(8.dp))
            TilePicker(
                options = ApartmentType.values().toList(),
                selected = shared.apartmentType,
                onSelect = { t -> viewModel.setApartmentType(t, shared.apartmentTypeOtherText) },
                label = { it.label() },
            )
            Spacer(Modifier.height(8.dp))
            Text("Количество гостей (авто): $mainGuests", style = MaterialTheme.typography.bodyMedium)
            Spacer(Modifier.height(8.dp))
            Row(horizontalArrangement = Arrangement.spacedBy(8.dp)) {
                DateField("Заезд", shared.checkinDate(), viewModel::setCheckinDate, Modifier.weight(1f))
                DateField("Выезд", shared.checkoutDate(), viewModel::setCheckoutDate, Modifier.weight(1f))
            }
            Spacer(Modifier.height(8.dp))
            MoneyField("Стоимость за сутки", shared.dailyRate, viewModel::setDailyRate, Modifier.fillMaxWidth())
            Spacer(Modifier.height(8.dp))
            MoneyField("Депозит", shared.deposit, viewModel::setDeposit, Modifier.fillMaxWidth())
            Spacer(Modifier.height(8.dp))
            Text("Итого: ${shared.total().formatMoney()}", style = MaterialTheme.typography.titleSmall)
            Spacer(Modifier.height(20.dp))
        }

        items(extras, key = { it.localId }) { obj ->
            ExtraObjectCard(obj, cityOptions, onChange = { t -> viewModel.updateExtraObject(obj.localId, t) }, onRemove = { viewModel.removeExtraObject(obj.localId) })
            Spacer(Modifier.height(12.dp))
        }

        item {
            OutlinedButton(onClick = viewModel::addExtraObject, modifier = Modifier.fillMaxWidth()) { Text("+ Добавить объект") }
            Spacer(Modifier.height(20.dp))
            Divider()
            Spacer(Modifier.height(12.dp))

            Text("Шаблон объекта (редактируемый)", style = MaterialTheme.typography.titleSmall)
            Spacer(Modifier.height(8.dp))
            OutlinedTextField(value = template, onValueChange = viewModel::updateTemplate, modifier = Modifier.fillMaxWidth(), minLines = 6)
            Spacer(Modifier.height(16.dp))

            Text("Готовый текст", style = MaterialTheme.typography.titleSmall)
            Spacer(Modifier.height(8.dp))
            CopyableTextBlock(generated)
            Spacer(Modifier.height(24.dp))

            Button(onClick = viewModel::saveToRegistry, modifier = Modifier.fillMaxWidth()) { Text("Сохранить в реестр") }
            Spacer(Modifier.height(24.dp))
            Divider()
            Spacer(Modifier.height(12.dp))
            Text("Реестр согласований с финансами", style = MaterialTheme.typography.titleMedium)
            Spacer(Modifier.height(8.dp))
        }

        items(registry, key = { it.id }) { entry ->
            RegistryRow(
                entry = entry,
                checked = entry.id in checkedIds,
                onCheckedChange = { viewModel.toggleRegistryChecked(entry.id) },
                onDelete = { viewModel.deleteRegistryEntry(entry) },
            )
        }

        item {
            Spacer(Modifier.height(12.dp))
            Row(horizontalArrangement = Arrangement.spacedBy(8.dp)) {
                Button(onClick = viewModel::addCheckedRowsAsObjects, modifier = Modifier.weight(1f)) {
                    Text("➕ Добавить выбранные как объекты")
                }
            }
            Spacer(Modifier.height(8.dp))
            OutlinedButton(onClick = { exportLauncher.launch("Реестр согласований.xlsx") }, modifier = Modifier.fillMaxWidth()) {
                Text("Скачать Excel")
            }
            Spacer(Modifier.height(32.dp))
        }
    }
}

@Composable
private fun ExtraObjectCard(
    obj: ExtraFinanceObject,
    cityOptions: List<String>,
    onChange: ((ExtraFinanceObject) -> ExtraFinanceObject) -> Unit,
    onRemove: () -> Unit,
) {
    Card {
        androidx.compose.foundation.layout.Column(Modifier.padding(12.dp)) {
            Row(horizontalArrangement = Arrangement.SpaceBetween, modifier = Modifier.fillMaxWidth()) {
                Text("Дополнительный объект", style = MaterialTheme.typography.titleSmall)
                IconButton(onClick = onRemove) { Icon(Icons.Filled.Close, contentDescription = "Удалить объект") }
            }
            AutosuggestTextField("Город", obj.city, { v -> onChange { it.copy(city = v) } }, cityOptions, Modifier.fillMaxWidth())
            Spacer(Modifier.height(8.dp))
            OutlinedTextField(obj.fullName, { v -> onChange { it.copy(fullName = v) } }, label = { Text("ФИО") }, modifier = Modifier.fillMaxWidth())
            Spacer(Modifier.height(8.dp))
            TilePicker(
                options = ApartmentType.values().toList(),
                selected = obj.apartmentType,
                onSelect = { t -> onChange { it.copy(apartmentType = t) } },
                label = { it.label() },
            )
            Spacer(Modifier.height(8.dp))
            OutlinedTextField(
                value = if (obj.guestsCount == 0) "" else obj.guestsCount.toString(),
                onValueChange = { v -> onChange { it.copy(guestsCount = v.filter { c -> c.isDigit() }.toIntOrNull() ?: 0) } },
                label = { Text("Количество гостей") },
                keyboardOptions = KeyboardOptions(keyboardType = KeyboardType.Number),
                modifier = Modifier.fillMaxWidth(),
            )
            Spacer(Modifier.height(8.dp))
            Row(horizontalArrangement = Arrangement.spacedBy(8.dp)) {
                DateField("Заезд", obj.checkinDate, { d -> onChange { it.copy(checkinDate = d) } }, Modifier.weight(1f))
                DateField("Выезд", obj.checkoutDate, { d -> onChange { it.copy(checkoutDate = d) } }, Modifier.weight(1f))
            }
            Spacer(Modifier.height(8.dp))
            MoneyField("Стоимость за сутки", obj.dailyRate, { v -> onChange { it.copy(dailyRate = v) } }, Modifier.fillMaxWidth())
            Spacer(Modifier.height(8.dp))
            MoneyField("Депозит", obj.deposit, { v -> onChange { it.copy(deposit = v) } }, Modifier.fillMaxWidth())
            Spacer(Modifier.height(8.dp))
            OutlinedTextField(obj.comment, { v -> onChange { it.copy(comment = v) } }, label = { Text("Комментарий") }, modifier = Modifier.fillMaxWidth())
            Spacer(Modifier.height(8.dp))
            Text("Итого: ${obj.total.formatMoney()}", style = MaterialTheme.typography.bodyMedium)
        }
    }
}

@Composable
private fun RegistryRow(
    entry: com.hrhousing.app.data.db.entity.FinanceRegistryEntryEntity,
    checked: Boolean,
    onCheckedChange: () -> Unit,
    onDelete: () -> Unit,
) {
    Row(verticalAlignment = Alignment.CenterVertically, modifier = Modifier.fillMaxWidth().padding(vertical = 4.dp)) {
        Checkbox(checked = checked, onCheckedChange = { onCheckedChange() })
        androidx.compose.foundation.layout.Column(Modifier.weight(1f)) {
            Text("${entry.city} — ${entry.fullName}", style = MaterialTheme.typography.bodyMedium)
            Text(
                "${TimeUtils.format(entry.checkinDate)}–${TimeUtils.format(entry.checkoutDate)} · ${entry.total.formatMoney()}",
                style = MaterialTheme.typography.bodySmall,
            )
        }
        IconButton(onClick = onDelete) { Icon(Icons.Filled.Close, contentDescription = "Удалить") }
    }
    Divider()
}
