package com.hrhousing.app.ui.screens.booking

import androidx.compose.foundation.layout.Arrangement
import androidx.compose.foundation.layout.Row
import androidx.compose.foundation.layout.Spacer
import androidx.compose.foundation.layout.fillMaxWidth
import androidx.compose.foundation.layout.height
import androidx.compose.foundation.layout.padding
import androidx.compose.foundation.lazy.LazyColumn
import androidx.compose.material3.Divider
import androidx.compose.material3.MaterialTheme
import androidx.compose.material3.OutlinedTextField
import androidx.compose.material3.Text
import androidx.compose.runtime.Composable
import androidx.compose.runtime.collectAsState
import androidx.compose.runtime.getValue
import androidx.compose.ui.Modifier
import androidx.compose.ui.unit.dp
import androidx.lifecycle.viewmodel.compose.viewModel
import com.hrhousing.app.AppContainer
import com.hrhousing.app.data.db.entity.ApartmentType
import com.hrhousing.app.data.db.entity.label
import com.hrhousing.app.data.shared.checkinDate
import com.hrhousing.app.data.shared.checkoutDate
import com.hrhousing.app.data.shared.total
import com.hrhousing.app.ui.AppViewModelFactory
import com.hrhousing.app.ui.components.AutosuggestTextField
import com.hrhousing.app.ui.components.CopyableTextBlock
import com.hrhousing.app.ui.components.DateField
import com.hrhousing.app.ui.components.DynamicNameList
import com.hrhousing.app.ui.components.MoneyField
import com.hrhousing.app.ui.components.TilePicker
import com.hrhousing.app.ui.components.TimeTextField
import com.hrhousing.app.util.formatMoney

@Composable
fun BookingScreen(container: AppContainer) {
    val viewModel: BookingViewModel = viewModel(factory = AppViewModelFactory(container))
    val shared by viewModel.sharedFields.collectAsState()
    val template by viewModel.template.collectAsState()
    val generated by viewModel.generatedText.collectAsState()
    val cityOptions by viewModel.cityOptions.collectAsState()

    LazyColumn(modifier = Modifier.fillMaxWidth().padding(16.dp)) {
        item {
            Text("Гости", style = MaterialTheme.typography.titleSmall)
            DynamicNameList(shared.guestNames, viewModel::setGuestNames, label = "ФИО гостя")
            Spacer(Modifier.height(12.dp))

            AutosuggestTextField("Город", shared.city, viewModel::setCity, cityOptions, Modifier.fillMaxWidth())
            Spacer(Modifier.height(8.dp))
            OutlinedTextField(shared.complexName, viewModel::setComplexName, label = { Text("ЖК") }, modifier = Modifier.fillMaxWidth())
            Spacer(Modifier.height(8.dp))
            OutlinedTextField(shared.address, viewModel::setAddress, label = { Text("Адрес") }, modifier = Modifier.fillMaxWidth())
            Spacer(Modifier.height(12.dp))

            Text("Тип квартиры", style = MaterialTheme.typography.titleSmall)
            TilePicker(
                options = ApartmentType.values().toList(),
                selected = shared.apartmentType,
                onSelect = { type -> viewModel.setApartmentType(type, shared.apartmentTypeOtherText) },
                label = { it.label() },
            )
            if (shared.apartmentType == ApartmentType.OTHER) {
                Spacer(Modifier.height(8.dp))
                OutlinedTextField(
                    shared.apartmentTypeOtherText,
                    { v -> viewModel.setApartmentType(ApartmentType.OTHER, v) },
                    label = { Text("Тип квартиры (другое)") },
                    modifier = Modifier.fillMaxWidth(),
                )
            }
            Spacer(Modifier.height(12.dp))

            Row(horizontalArrangement = Arrangement.spacedBy(8.dp)) {
                DateField("Дата заезда", shared.checkinDate(), viewModel::setCheckinDate, Modifier.weight(1f))
                DateField("Дата выезда", shared.checkoutDate(), viewModel::setCheckoutDate, Modifier.weight(1f))
            }
            Spacer(Modifier.height(8.dp))
            Row(horizontalArrangement = Arrangement.spacedBy(8.dp)) {
                TimeTextField("Время заезда", shared.checkinTime, viewModel::setCheckinTime, Modifier.weight(1f))
                TimeTextField("Время выезда", shared.checkoutTime, viewModel::setCheckoutTime, Modifier.weight(1f))
            }
            Spacer(Modifier.height(12.dp))

            MoneyField("Стоимость за сутки", shared.dailyRate, viewModel::setDailyRate, Modifier.fillMaxWidth())
            Spacer(Modifier.height(8.dp))
            MoneyField("Депозит", shared.deposit, viewModel::setDeposit, Modifier.fillMaxWidth())
            Spacer(Modifier.height(8.dp))
            Text("Итого: ${shared.total().formatMoney()}", style = MaterialTheme.typography.titleMedium)
            Spacer(Modifier.height(20.dp))
            Divider()
            Spacer(Modifier.height(12.dp))

            Text("Шаблон (редактируемый)", style = MaterialTheme.typography.titleSmall)
            Spacer(Modifier.height(8.dp))
            OutlinedTextField(
                value = template,
                onValueChange = viewModel::updateTemplate,
                modifier = Modifier.fillMaxWidth(),
                minLines = 6,
            )
            Spacer(Modifier.height(16.dp))

            Text("Готовый текст", style = MaterialTheme.typography.titleSmall)
            Spacer(Modifier.height(8.dp))
            CopyableTextBlock(generated)
            Spacer(Modifier.height(32.dp))
        }
    }
}
